name: Workflow Main

on:
  push:
    branches: 
      - "main"

jobs:
  
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Save SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Set permissions for SSH private key
        run: chmod 600 ~/.ssh/id_rsa

      - name: Update known hosts
        run: ssh-keyscan "${{ secrets.IP_REMOTE }}" >> ~/.ssh/known_hosts

      - name: Connect to EC2 and execute commands
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.USER_REMOTE }}"@"${{ secrets.IP_REMOTE }}" "cd folder_project && docker compose down && docker compose pull && docker compose build && docker compose up -d && exit"
  